name: Launch and Terminate EC2 Instance

on:
  workflow_dispatch:
    inputs:
      ami_id:
        description: 'AMI ID for the EC2 instance'
        required: true
      instance_type:
        description: 'EC2 instance type (e.g., t2.micro)'
        required: true
      key_name:
        description: 'Key pair name'
        required: true
      security_group:
        description: 'Security group name'
        required: true
      instance_id:
        description: 'EC2 Instance ID to terminate (optional)'
        required: false
        default: ''

jobs:
  manage-ec2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Launch EC2 instance
      run: |
        echo "Launching EC2 instance with AMI ID: ${{ github.event.inputs.ami_id }}"
        aws ec2 run-instances \
          --image-id ${{ github.event.inputs.ami_id }} \
          --instance-type ${{ github.event.inputs.instance_type }} \
          --key-name ${{ github.event.inputs.key_name }} \
          --security-groups ${{ github.event.inputs.security_group }}

    - name: Terminate EC2 instance (if instance_id is provided)
      if: ${{ github.event.inputs.instance_id != '' }}
      run: |
        echo "Terminating instance: ${{ github.event.inputs.instance_id }}"
        aws ec2 terminate-instances --instance-ids ${{ github.event.inputs.instance_id }}
