name: Launch and Terminate EC2 Instance

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      instance_id:
        description: 'EC2 Instance ID to terminate'
        required: false
        default: ''

jobs:
  launch-ec2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Launch EC2 instance
      run: |
        aws ec2 run-instances \
          --image-id ami-084568db4383264d4 \
          --instance-type t2.micro \
          --key-name Hcl-prac-training \
          --security-groups test-prac-nvirg-sg

    - name: Terminate EC2 instance (if instance_id is provided)
      if: ${{ github.event.inputs.instance_id != '' }}
      run: |
        echo "Terminating instance: ${{ github.event.inputs.instance_id }}"
        aws ec2 terminate-instances --instance-ids ${{ github.event.inputs.instance_id }}
