name: Creation of EC2 Instance with OIDC

on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'Choose action: launch or destroy'
        required: true
        type: choice
        options:
          - launch
          - destroy
      ami_id:
        description: 'AMI ID (required for launch)'
        required: false
      instance_type:
        description: 'Instance type (e.g., t2.micro) (required for launch)'
        required: false
      key_name:
        description: 'Key pair name (required for launch)'
        required: false
      security_group:
        description: 'Security group name (required for launch)'
        required: false
      instance_id:
        description: 'Instance ID (required for terminate)'
        required: false
        
permissions:
  id-token: write
  contents: read
  
jobs:
  manage-ec2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::211125784755:role/OIDC-auth-GA
        aws-region: us-east-1

    - name: Launch EC2 instance
      if: ${{ github.event.inputs.mode == 'launch' }}
      run: |
        echo "Launching EC2 instance..."
        aws ec2 run-instances \
          --image-id ${{ github.event.inputs.ami_id }} \
          --instance-type ${{ github.event.inputs.instance_type }} \
          --key-name ${{ github.event.inputs.key_name }} \
          --security-groups ${{ github.event.inputs.security_group }}

    - name: Terminate EC2 instance
      if: ${{ github.event.inputs.mode == 'destroy' }}
      run: |
        echo "Terminating EC2 instance: ${{ github.event.inputs.instance_id }}"
        aws ec2 terminate-instances --instance-ids ${{ github.event.inputs.instance_id }}
